---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deploy
  labels:
    app: demo-voting-app
    name: postgres-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-voting-app
      name: postgres-pod
  template:
    metadata:
      name: postgres-pod
      labels:
        name: postgres-pod
        app: demo-voting-app
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"


---
apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  labels:
    name: postgres-svc
    app: demo-voting-app
spec:
  type: ClusterIP
  selector:
    app: demo-voting-app
    name: postgres-pod
  ports:
    - port: 5432
      targetPort: 5432
