---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-deploy
  labels:
    name: result-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: result-pod
  template:
    metadata:
      name: result-pod
      labels:
        name: result-pod
    spec:
      containers:
        - name: result-app
          image: srikanthvelma/voting-app_result:v1
          ports:
            - containerPort: 80


---
apiVersion: v1
kind: Service
metadata:
  name: result-svc
  labels:
    name: result-svc
spec:
  type: NodePort  
  selector:
    name: result-pod
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30005

    
