---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-deploy
  labels:
    name: voting-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: voting-pod
  template:
    metadata:
      name: voting-pod
      labels:
        name: voting-pod
    spec: 
      containers:
        - name: voting-app
          image: srikanthvelma/voting-app_vote:v1
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service 
metadata:
  name: voting-svc
  labels:
    name: voting-svc
spec:
  type: NodePort
  selector:
    name: voting-pod
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30004
