apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deploy
  labels:
    app: demo-voting-app
    name: worker-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: worker-pod
  template:
    metadata:
      name: worker-pod
      labels:
        name: worker-pod
    spec:
      containers:
        - name: worker-app
          image: srikanthvelma/voting-app_worker:v1